### ISSUE TITLE
Thanks, and maybe a bug?

### ISSUE THREAD

**Issue by tomkail** [bleppie/Blep.TextureOps#1]
Hi! This code is GOLD. Thanks so much for putting it together!

Wanted to report a couple of maybe-bugs.
In Gaussian Blur, sigma is calculated automatically as `if (sigma < 0) sigma = sigma = size / 4;`. For one thing sigma is set twice, but the main issue is that I had thought that sigma was normally calculated as radius/3; which would mean /6 here? I guess it's more a preference anyway.
In the same function, `int ys` is calculated but unused - xs is used for x and y. Is that an oversight?

Ta!

**Comment by bleppie** [comment]
Fixed in commit 73f1cb1
